name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the project
        run: |
          cd frontend
          npm run build

      - name: Deploy to cPanel
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          CPANEL_SERVER: ${{ secrets.CPANEL_SERVER }}
          CPANEL_PATH: ${{ secrets.CPANEL_PATH }}
        run: |
          sshpass -p $CPANEL_PASSWORD ssh -o StrictHostKeyChecking=no $CPANEL_USER@$CPANEL_SERVER << 'EOF'
          # Navigate to the deployment directory
          cd $CPANEL_PATH

          # Preserve .htaccess and .well-known folders, and backup existing files
          rsync -av --exclude='.git' --exclude='dist' --exclude='.well-known' --exclude='.htaccess' $CPANEL_PATH/ /tmp/deploy/
          rm -rf $CPANEL_PATH/*
          rsync -av /tmp/deploy/ $CPANEL_PATH/
          EOF

          # Deploy the new build files
          rsync -av ${{ github.workspace }}/frontend/dist/ $CPANEL_USER@$CPANEL_SERVER:$CPANEL_PATH/

      - name: Verify deployment
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          CPANEL_SERVER: ${{ secrets.CPANEL_SERVER }}
          CPANEL_PATH: ${{ secrets.CPANEL_PATH }}
        run: |
          sshpass -p $CPANEL_PASSWORD ssh -o StrictHostKeyChecking=no $CPANEL_USER@$CPANEL_SERVER << 'EOF'
          echo "Verifying deployment..."
          ls -la $CPANEL_PATH/
          EOF
